[package]
name = "google-jwt-verify"
version = "0.1.0"
authors = ["Nathan Fox <fuchsnj@gmail.com>"]

[dependencies]
openssl = "0.10.7"
base64 = "0.9.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
reqwest = "0.8.5"